### ISSUE TITLE
intel has some potential mutex_destroy missing issues.

### ISSUE THREAD

**Issue by mrgtwentythree** [riastradh/netbsd-src#25]
chuq reports:

 kern info: [drm] failed to retrieve link info, disabling eDP
 Mutex error: kmem_intr_free,286: allocation contains active lock 
 lock address : 0xffffac57394a1258 type     :     sleep/adaptive 
 initialized  : 0xffffffff80c5fc8a 
 shared holds :                  0 exclusive:                  0 
 shares wanted:                  0 exclusive:                  0 
 relevant cpu :                  1 last held:                  1 
 relevant lwp : 0xffffac57391b0180 last held: 000000000000000000 
 last locked  : 0xffffffff80c5f01b unlocked*: 0xffffffff80c5f0c9 
 owner field  : 000000000000000000 wait/spin:                0/0 
 Turnstile: no active turnstile for this lock. 
 panic: LOCKDEBUG: Mutex error: kmem_intr_free,286: allocation contains active lock 
 cpu1: Begin traceback... 
 vpanic() at netbsd:vpanic+0x156 
 device_printf() at netbsd:device_printf 
 lockdebug_more.part.0() at netbsd:lockdebug_more.part.0 
 kmem_intr_free() at netbsd:kmem_intr_free+0x99 
 intel_modeset_init() at netbsd:intel_modeset_init+0x226a 
 i915_driver_probe() at netbsd:i915_driver_probe+0x936 
 i915drmkms_attach_real() at netbsd:i915drmkms_attach_real+0x4c 
 config_mountroot_thread() at netbsd:config_mountroot_thread+0x60 

with additional info:

0xffffffff8073b17c <intel_modeset_init+8805>:        callq  0xffffffff80718dd4 <intel_ddi_init>
0xffffffff80c5fc85 <drm_dp_aux_init+23>:     callq  0xffffffff80e45916 <mutex_init>
0xffffffff80c5f016 <drm_dp_dpcd_access+55>:  callq  0xffffffff80e459df <mutex_vector_enter>
0xffffffff80c5f0c4 <drm_dp_dpcd_access+229>: callq  0xffffffff80e461cf <mutex_vector_exit>

surveying the code, i don't see mutex_destroy() for at least these:

dist/drm/i915/display/intel_psr.c:      mutex_init(&dev_priv->psr.lock);
dist/drm/i915/display/intel_tc.c:       mutex_init(&dig_port->tc_lock);

one problem is that intel_tc_port_init() has no _fini().  i do not know if these
are related to the specific crash, but i believe tc_lock is the problematic one.

**Comment by chucksilvers** [comment]
It looks to me like it's this mutex_enter() at the top of drm_dp_dpcd_access():

mutex_lock(&aux->hw_mutex);

that mutex is destroyed in drm_dp_aux_unregister(), but the unregister is not called in the err path that we take here.  I'll mail you a diff because github's UI won't let me attach it here.

**Comment by riastradh** [comment]
fixed in 83b864c356e391400345e7da845821e00e4f67ec?

**Comment by chucksilvers** [comment]
yup, that fixes the assert failure.  I still get the black screen but that's a different problem.
